= Overview of {product}

Get to know the basics of {product} with these tours.

[cols="2*^", %noheader, frame=none, grid=none]
|===
a|image::icon_syson_black.svg[xref=user-manual:what-is.adoc]

**What is {product}?**

{product}'s mission to make {sysmlv2} models accessible to everyone.

xref:user-manual:what-is.adoc[Learn more...] a|image::overview.svg[xref=user-manual:sysmlv2-overview.adoc]

**Overview of {sysmlv2}**

Delve into the foundational concepts of {sysmlv2}.

xref:user-manual:sysmlv2-overview.adoc[Learn more...]

a| image::developer_guide.svg[xref=user-manual:key-features.adoc]

**Key features in {product}?**

Explore {product} key features and benefits.

xref:user-manual:key-features.adoc[Learn more...] a|image::globe.svg[xref=user-manual:features/capella.adoc]

**MBSE, Capella and {product}?**

Integration between {product}, the MBSE ecosystem and Capella.

xref:user-manual:features/capella.adoc[Learn more...]

a| image::hub.svg[xref=user-manual:features/interoperability.adoc]

**Interoperability**

Commitment to interoperability and standard APIs support for seamless connections.

xref:user-manual:features/interoperability.adoc[Learn more...] a|image::diversity.svg[xref=user-manual:help.adoc]

**Community**

Get help about {product}.

xref:user-manual:help.adoc[Learn more...]
|===