= Create Your First Model

This tutorial provides a beginner-friendly guide on creating your first {sysmlv2} model with {product}, adapted from the example in the https://github.com/MBSE4U/dont-panic-batmobile[Don't Panic - The Absolute Beginner's Guide to SysML v2] book by Tim Weilkiens and Christian Muggeo.
The focus is on representing the Batmobile system, the iconic car of Batman.

== Step 1: Create a Project

. Open the {homepage} and xref:hands-on/how-tos/create-template-project.adoc[create a new {sysmlv2} project] by clicking on the {sysmlv2} card.
. The {editor} automatically opens, creating a new project named `{sysmlv2}` with a package `Package1`.
A default `{gv}` representation associated with the package is opened in the main editor area.
. From the project toolbar, xref:hands-on/how-tos/rename-project.adoc[rename the project] to `Batmobile`.
. From the {explorer}, xref:hands-on/how-tos/rename-model.adoc[rename the model] to `Batmobile` and the xref:hands-on/how-tos/rename-element.adoc[package] to `User Model`.

== Step 2: Create Elements from a Diagram

=== Using the {diag-toolbar}

. In the main editor area, click on the diagram background to open the {diag-toolbar}.
. Click on the `New Part Definition` tool to create a new part definition.
NOTE: The new elements created from the {diag-toolbar} are visible either from the {explorer} or the {editor} main central area.
. Rename the part definition to `Vehicle` using the xref:hands-on/how-tos/update-element.adoc#representation[direct-edit action] or the xref:hands-on/how-tos/update-element.adoc#details[{details} view].
. Select the `Vehicle` part definition and click on the `Nested Item Usage` tool to create an item usage.
. Rename the item usage to `driver`.
. Select the `Vehicle` part definition and click on the `Nested Part Usage` tool to create a new part usage.
. Rename the part usage to `engine`.

=== Setting Multiplicity

. Select the `Vehicle` part definition and click on the `Nested Part Usage` tool in the {diag-toolbar} to create a new part usage
. Rename the part usage to `wheels`.
. Select the relationship between `Vehicle` and `wheels`, set the multiplicity label to `[4]`.

=== Using Drag and Drop

. Select the `wheels` part usage, rename it `wheels[4]:Wheel`.
. A new `Wheel` part definition is created in the model.
. Drag and drop the `Wheel` element from the {explorer} onto the diagram background.
. The `Wheel` part definition appears on the diagram within the `Typed By` relationship between the `Wheel` and the `wheels` part usage.

== Step 3: Edit the Model Elements

=== Adding Attributes

. Select the `attributes` compartment in the `Vehicle` part definition and click on the `New Attribute Usage` tool in the {diag-toolbar}.
. A new attribute usage is created.
. Select the attribute and use the direct-edit tool to rename it to `actualSpeed : SpeedUnit`
. A new attribute definition named `SpeedUnit` is created automatically
. The attribute usage `actualSpeed` is typed with the new attribute definition.

=== Creating Specialization

. Click on the diagram background and click on the `New Part Definition` tool.
. A new part definition is created.
. Rename it `Batmobile:> Vehicle`.
. A new `specialization` relationship is created between the `Batmobile` part definition and the `Vehicle` part definition.

=== Creating Subsetting

. Click on the diagram background and select the `New Part Usage` tool.
. A new part usage is created.
. Rename it to `frontRightWheel :> wheels`.
. A new `subsetting` relationship appears between the two parts usages `frontRightWheel` and `wheels`.

=== Creating Redefinition

. Click on the diagram background and click on the `New Part Definition` tool.
. A new part definition is created.
. Rename it to `bulletProofWheels[4]:>>wheels`.
. A new `redefines` relationship appears between the `bulletProofWheels` part definition and the`wheels` part usage.

NOTE: To explore a more complete Batmobile example, use the Batmobile template available on the {homepage}.