= Get help

== Where can you get help ?

=== Community support
// Details Forums, Q&A, chat, mailing lists, news groups, social networks… any service where users discuss and support each others
* https://product-name/forum[Forum] - Remember to prefix the subject of your {product-name}-related posts with "[{Product-name}]"
// Details how the community can report bugs and improvement/feature requests, and follow the work done on the project.
* {bug}[Bug tracker] - Review and create issues
* https://github.com/product-name/issues/new[File a bug] - File bugs and feature requests

=== Professional services
// Describes from a user point of view how to ask for help, from a team point of view how are we organized (bug triage, discussion platform assistance...).
{product-name} offers support for all our users! We currently provide email-based support which we’ve found to be most effective for a number of reasons.

It’s easy for our support team to triage conversations and get them to the right people quickly. This helps us get you the answers you need so you can get back to modeling. It’s also easy for users to attach files, videos, and screenshots that our support team might need for troubleshooting more complicated issues.

When you need us, we’re here to help.

https://www.obeosoft.com/fr/contact[Contact the {product-name} support team]

==== What are {product-name} support hours ?

Our support team members are in Europe.

Support hours: Monday through Friday 9am - 5pm (CET / UTC +01).