site:
  title: SysOn documentation
  start_page: syson::index.adoc

output:
  clean: true

content:
  sources:
    - url: /usr/app
      start_paths: doc/content
      branches: HEAD

ui:
  bundle:
    url: /home/antora/ui-bundle.zip

asciidoc:
  attributes:
    icons: font
    icon-set: fas
    sectanchors:
    sectlinks:
    sectnums: all
    page-toclevels: 3
